language: groovy
script:
  # This is calling Bintray API for uploading the artifact to Bintray, Under the existing tr_demo package an new version will be created 
  # with the Travis build number which will contain the artifacts
  - curl -T bintray.png -uophirh:$KEY https://api.bintray.com/content/ophirh/demo/tr_demo/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/bintray.png
  # This is calling Bintray API for publishing the new version with its artifacts
  - curl -XPOST -uophirh:$KEY https://api.bintray.com/content/ophirh/demo/tr_demo/$TRAVIS_JOB_NUMBER/publish
  - curl -XGET https://bintray.com/ophirh/demo/tr_demo/$TRAVIS_JOB_NUMBER

